services:
  api:
    build: ./app/api
    env_file:
      - .env
    ports:
      - "${POMODORO_PORT:-9998}:${POMODORO_PORT:-9998}"
    restart: always

  web:
    build: ./app/web
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: always
